### ISSUE TITLE
Avoid using non-LTS Node.js versions

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-integrations-common#2]
Node 21 EOT is scheduled for 2024-06-01. Let's use @20 (2026-04-30) or @18 (2025-04-30) like the rest of CKEditor 5 packages.

**Comment by Mati365** [comment]
Fixed https://github.com/ckeditor/ckeditor5-integrations-common/pull/1/commits/175b890c2fc134d7d6e5308deafe65697e76dc16
