### ISSUE TITLE
Decide to use `yarn` or `npm`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-integrations-common#3]
Almost all CKEditor 5 packages use `yarn`. This repository uses `npm`.

We should follow the same rules to avoid confusion when working with different repositories.

**Comment by Mati365** [comment]
Switched to `yarn`. https://github.com/ckeditor/ckeditor5-integrations-common/pull/1/commits/b95c2911135191485f957c54ada1728fe7eab550
