### ISSUE TITLE
The `pre-commit` script misses the license header

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-integrations-common#4]
https://github.com/ckeditor/ckeditor5-integrations-common/blob/047ca8658cf1c3239e08a5a89c69a0e3c775e575/.husky/pre-commit

**Comment by Mati365** [comment]
Fixed https://github.com/ckeditor/ckeditor5-integrations-common/pull/1/commits/efc63a7734b983aa5fb6cfe34228e16238887bb0
