### ISSUE TITLE
Decide the name of the main branch

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-integrations-common#5]
Should it `#main` as currently or `#master` as all of CKEditor 5 repositories follow?

Whatever we decide, several scripts need to be aligned:

* https://github.com/ckeditor/ckeditor5-integrations-common/blob/047ca8658cf1c3239e08a5a89c69a0e3c775e575/.circleci/config.yml#L290
* https://github.com/ckeditor/ckeditor5-integrations-common/blob/047ca8658cf1c3239e08a5a89c69a0e3c775e575/scripts/utils/parsearguments.js#L29

And perhaps more. I did not scan the entire repository.

**Comment by Mati365** [comment]
Renamed to master https://github.com/ckeditor/ckeditor5-integrations-common/pull/1/commits/3b5a5a803b87a674af2aacff8448220207b6549f

**Comment by pomek** [comment]
Reopening as CircleCI config was not updated.

https://github.com/ckeditor/ckeditor5-integrations-common/blob/014db38bb49624dbb039cc6bda7f87771101c5b1/.circleci/config.yml#L259

**Comment by pomek** [comment]
Green on master, so it works as expected. Let's close.
