### ISSUE TITLE
package.json#version should be 0.0.1

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-integrations-common#6]
Unavailable CKEditor 5 packages on npm yet use the `0.0.1` version.

https://github.com/ckeditor/ckeditor5-integrations-common/blob/047ca8658cf1c3239e08a5a89c69a0e3c775e575/package.json#L3

**Comment by Mati365** [comment]
Fixed https://github.com/ckeditor/ckeditor5-integrations-common/pull/1/commits/4e4631219c0d04c2757b162f3e2e75b466b3c45b
